### ISSUE TITLE
TODO: Back-end: Submit and Results support

### ISSUE THREAD

**Issue by awatemonosan** [Lusty-Lobster/Lusty-Lobster#15]
- [x] respond to get requests at /api/client with a list of submitted requests
```
response = {
  results:{
    [
      { id:boolean, status:boolean },
      { id:boolean, status:boolean },
      { id:boolean, status:boolean },
      ...
    ]
  }
}
```
- [x] respond to get requests at /api/client/?id with the task object associated with that request.
- [x] allow post requests at /api/client to submit new requests

**Comment by awatemonosan** [comment]
Complete
