### ISSUE TITLE
TODO: Back-end: support array of tasks

### ISSUE THREAD

**Issue by awatemonosan** [Lusty-Lobster/Lusty-Lobster#9]
- [x] create Task class with the following properties:
  - alg: a string containing the javascript code to run
  - data: an array containing the data to crunch
  - result: the returned result from the cruncher. Defaults to undefined.
- [x] create an array called tasks that holds all of the Task objects.
- [x] when a get request comes in, pop a task and send it to the cruncher
